### ISSUE TITLE
Custom key functions

### ISSUE THREAD

**Issue by ajjohnston** [PatrickJS/redis-dataloader#2]
Currently,  the `makeKey` function takes in a key which it assumes to be a string and returns the templated keyspace + key string.

Ideally, I would be able to write my own makeKey function to handle object keys and other non-primitive types. I think being able to use the `cacheKeyFn` option in https://github.com/facebook/dataloader as an override for `makeKey` would be a good solution.

**Comment by DubFriend** [comment]
Ok yea this is totally useful. I have added the option for a `cacheKeyFn` option that should work basically the same as the facebook version.

By default, the "cacheKeyFn" will serialize objects and arrays using [json-stable-stringify](https://github.com/substack/json-stable-stringify) and allow all other values to pass through unchanged.

Changes available in version `0.4.1`
