### ISSUE TITLE
isIORedis flag is always false, even while using ioredis

### ISSUE THREAD

**Issue by kannanmavila** [PatrickJS/redis-dataloader#7]
`isIORedis` [flag](https://github.com/DubFriend/redis-dataloader/blob/master/index.js#L9) is supposed to be `true` if the underlying library is `ioredis`. But it's always false, as even `ioredis` uses the `Redis` class from `redis`.

As a result, [this line](https://github.com/DubFriend/redis-dataloader/blob/master/index.js#L54) is never hit. If you're using `ioredis` (like me), you'll run into an error on [this line](https://github.com/DubFriend/redis-dataloader/blob/master/index.js#L19), that says:
> SyntaxError: Unexpected token , in JSON at position 0

Why this happens: The `resp` object on [this line](https://github.com/DubFriend/redis-dataloader/blob/master/index.js#L19) is expected to be a string, but due to the bug, ends up being a list.

**Interesting note:**
The submitter of [this issue](https://github.com/DubFriend/redis-dataloader/issues/4) has actually fixed this bug in his code. See [this line](https://github.com/scf4/ioredis-dataloader/blob/master/index.js#L38).

**Comment by faceleg** [comment]
I’m considering this library with ioredis. Is this bug still present?

**Comment by kannanmavila** [comment]
I ended up not using the library because of this issue. Hence not sure. I ended up writing my own version.

**Comment by jgcmarins** [comment]
@kannanmavila is it open source?

**Comment by kannanmavila** [comment]
I wrote it at work. So, unfortunately not.

**Comment by faceleg** [comment]
I did a similar thing - basically I used node-cache as the dataloader map (I wanted a TTL), and in my batch query I used redis.mget - for all of the values that don't exist in redis, I do my normal getter, then merge the lists together and return the result.

Mine isn't open source either, and I wouldn't share it because it's pretty abstracted.

It was surprisingly easy - have a go :)

**Comment by rmoura-92** [comment]
PR with fix: https://github.com/DubFriend/redis-dataloader/pull/11

**Comment by PatrickJS** [comment]
this is fixed now
